version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lamp_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html
    networks:
      - lamp-network

  db:
    image: mysql:8.0
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - lamp-network
  
  maildev:
    hostname: maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "1080:80"
      - "25:25"

networks:
  lamp-network:


volumes:
  db_data:
  web:
